- name: Only for Debian distro
  when: ansible_facts['os_family'] == "Debian"
  block:
    - name: Update and upgrade to their latest version
      apt:
        name: "*"
        state: latest

    - name: Install unattended-upgrades
      apt:
        name: unattended-upgrades
        state: present

    - name: Configure unattended-upgrades
      template:
        src: 50unattended-upgrades.j2
        dest: /etc/apt/apt.conf.d/50unattended-upgrades
        owner: root
        group: root
        mode: 0644
      vars:
        unattended_reboot:
          enabled: true
          time: 20:00

    - name: Periodic upgrades configured
      template:
        src: 10periodic.j2
        dest: /etc/apt/apt.conf.d/10periodic
        owner: root
        group: root
        mode: 0644